import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-doctor-details',
  templateUrl: './doctor-details.component.html',
  styleUrl: './doctor-details.component.css'
})
export class DoctorDetailsComponent {
  doctor: any;
  doctors=[
    {name:"Dr. Bhoopal T.S", slug:'Dr-Bhoopal-T-S', qualification:" MBBS, MD", designation:'Managing Director', image:'../../assets/doctor-1.png',about:'Aksha Hospital is the brainchild of Dr Bhoopal TS.It is the result of his dedication and hard work of his lifetime in the medical field. Dr Bhoopal TS, an eminent doctor, working since its inception in Sri Jayadeva Institute of Cardiology...'},
    {name:"Dr. Smitha Bhoopal ", slug:'Dr-Smitha-Bhoopal', qualification:"MBBS, DGO", designation:'Obstertrics & Gynaecologist', image:'../../assets/doctor-2.png',about:'Dr Smitha Bhoopal is a well-known Gynaecologist in South Bangalore has been working in both government and private healthcare sectors for 40 years. It has always been her dream to start a Super Speciality Hospital, which caters to all the sections of the society...'},
    {name:"Dr. Sumanth Bhoopal ", slug:'Dr-Sumanth-Bhoopal ', qualification:"MBBS, MS, FSGE", designation:'Medical Director of Aksha Hospital', image:'../../assets/doctor-3.png',about:'Dr. Sumanth Bhoopal is one of the most eminent doctors in the specialty of Surgical Gastroenterology & Interventional Endoscopy with over 17 years of expertise with 5000+ procedures. He holds vast experience in treating major and minor Gastroenterology...'},
    {name:"Dr. Madhuri Sumanth", slug:'Dr-Madhuri-Sumanth', qualification:"MBBS, MS (OBG & GYNAEC) & FMAS", designation:'Sr. Consultant (Obstetrics & Gynaecologist)', image:'../../assets/doctor-4.png',about:'Dr. Madhuri Sumanth’s practice is “Respect Motherhood” and delivering the best care for all pregnant ladies. She is an experienced and compassionate renowned obstetrician for Normal deliveries and handling high-risk pregnancies. She is best in her commitment...'},
    {name:"Dr. Deepa Rao", slug:'Dr-Deepa-Rao', qualification:"MBBS, DNB Family Medicine", designation:'Consultant – Family Physician', image:'../../assets/doctor-5.png',about:'After obtaining her MBBS degree from Government medical College, Bellary(VIMS) she went on to specialise in Family medicine from The Bangalore Hospital, Bangalore, and awarded Diplomate in national board,NBE, New Delhi.She has completed a Certificate... '},
    {name:"Dr. Kapil Wajapey", slug:'Dr-Kapil-Wajapey', qualification:"MBBS, DNB(Internal Medicine)", designation:'Consultant- Internal Medicine', image:'../../assets/doctor-6.png',about:'Dr Smitha Bhoopal is a well-known Gynaecologist in South Bangalore has been working in both government and private healthcare sectors for 40 years. It has always been her dream to start a Super Speciality Hospital, which caters to all the sections of the society...'},
    {name:"Dr. Sushal ShanthaKumar", slug:'Dr-Sushal-ShanthaKumar', qualification:"MBBS, MS (ORTHOPAEDICS)", designation:'Consultant - Arthroscopy & Shoulder Surgeon', image:'../../assets/doctor-7.png',about:'Dr. Sushal ShanthaKumar is one of the most eminent & top 5 Orthopedic Surgeons in Bengaluru, specializing in Knee and Shoulder: Sports Injuries using arthroscopic (keyhole) and minimally invasive surgeries with over 14 years of extensive experience. He has a vast...'},
    {name:"Dr. Anand Palakshachar", slug:'Dr-Anand-Palakshachar', qualification:"MBBS, MD General Medicine", designation:'Consultant- Cardiologist', image:'../../assets/doctor-8.png',about:'Dr Smitha Bhoopal is a well-known Gynaecologist in South Bangalore has been working in both government and private healthcare sectors for 40 years. It has always been her dream to start a Super Speciality Hospital, which caters to all the sections of the society...'},
    {name:"Dr. Prasad N A", slug:'Dr-Prasad-N-A', qualification:"MBBS, MD(Pediatrics), FIAP(Neonatology)", designation:'Consultant- Pediatrics & Neonatology', image:'../../assets/doctor-9.png',about:'Dr Smitha Bhoopal is a well-known Gynaecologist in South Bangalore has been working in both government and private healthcare sectors for 40 years. It has always been her dream to start a Super Speciality Hospital, which caters to all the sections of the society...'},
    {name:"Dr. Avani Hegde", slug:'Dr-Avani-Hegde', qualification:"MBBS, MD Pediatrics", designation:'Consultant- Pediatrician', image:'../../assets/doctor-10.png',about:'Dr. Avani Hegde completed her MD in Paediatrics from the Advanced Paediatric Centre, PGIMER, Chandigarh, where she was awarded the institutional bronze medal for her academic excellence. She pursued her sub-specialty training in paediatric and adolescent endocrinology...'},
    {name:"Dr. Vivekananda Kustagi", slug:'Dr-Vivekananda-Kustagi', qualification:"", designation:'', image:'../../assets/doctor-11.png',about:'Dr Smitha Bhoopal is a well-known Gynaecologist in South Bangalore has been working in both government and private healthcare sectors for 40 years. It has always been her dream to start a Super Speciality Hospital, which caters to all the sections of the society...'},
    {name:"Dr. Sridutt Shekar", slug:'Dr-Sridutt-Shekar', qualification:"MBBS, MS ENT", designation:'Consultant - ENT', image:'../../assets/doctor-12.png',about:'Dr. Sridutt Shekar is dedicated to providing top-notch care for patients with ear, nose, and throat conditions. His expertise spans a wide range of ENT procedures and treatments, ensuring comprehensive and effective care for his patients.'},
    {name:"Dr. Manju Aswath", slug:'Dr-Manju-Aswath', qualification:"MBBS, MD - Psychiatry", designation:'Consultant- Psychiatrist', image:'../../assets/doctor-13.png',about:'Dr. Manju Ashwath has dedicated over 20 years as a consultant psychiatrist, providing expert care in adult, child, and geriatric psychiatry, as well as in alcohol and substance abuse de-addiction. Her approach is comprehensive, integrating biological, psychological and...'},
    {name:"Dr. Santosh H S ", slug:'Dr-Santosh-H-S', qualification:"MBBS, FRCP, MRCP", designation:'Consultant - Endocrinologist', image:'../../assets/doctor-14.png',about:'Dr. Santosh HS brings over a decade of extensive training and experience in diabetes and endocrinology. He completed his MBBS from Bangalore University and earned his MRCP from the Royal College of Physicians in the UK. Dr. Santosh further honed his skills with specialist training...'},
    {name:"Dr. Sayalee Gadgil", slug:'Dr-Sayalee-Gadgil', qualification:"MBBS, DNB, FRCR(UK)", designation:'Consultant - ENT', image:'../../assets/doctor-15.png',about:'Dr. Sayalee Gadgil is dedicated to providing precise and detailed imaging services. Her expertise in fetal medicine and abdominal imaging ensures that patients receive accurate diagnoses and top-quality care.'},
  ]

  constructor(private route: ActivatedRoute) { }

  ngOnInit(): void {
    const doctorSlug = this.route.snapshot.paramMap.get('name');
    this.doctor = this.doctors.find(d => d.slug === doctorSlug);
  }
}
